inetpub/Ticketing.Website/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticketing.Framework.Mediators;
using Ticketing.Framework.Models.Cart;
using Ticketing.Framework.Models.Ticket;

namespace Ticketing.Website.Controllers
{
    public class CheckoutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Cart()
        {
            var mediator = new TicketMediator();
            CartVM model = mediator.GetCart();
            int i = 0;
            decimal total = 0;
            foreach (var perf in model.Performances)
            {
                perf.LineNumber = i;
                i++;
                total += (perf.Quantity * perf.Price);
            }
            model.Total = total;

            return View(model);
        }

        [HttpPost]
        public ActionResult Cart(CartVM cart)
        {
            return View(cart);
        }

        [HttpGet]
        public ActionResult Review()
        {
            var mediator = new TicketMediator();
            CartVM cart = mediator.GetCart();
            if (cart.Performances == null || cart.Performances.Count == 0)
                return Redirect("/checkout/cart");
            var model = new PaymentVM();
            model.SameAsBilling = true;
            return View("~/Views/Checkout/Review.cshtml", model);
        }

        [HttpPost]
        public ActionResult Review(PaymentVM model)
        {
            var oMediator = new OrderMediator();
            var tMediator = new TicketMediator();
            if (model.SameAsBilling)
            {
                model.ShippingAddress.Address1 = model.BillingAddress.Address1;
                model.ShippingAddress.City = model.BillingAddress.City;
                model.ShippingAddress.State = model.BillingAddress.State;
                model.ShippingAddress.Zip = model.BillingAddress.Zip;
            }
            var success = oMediator.CreateOrder(model);

            if (success)
            {
                //tMediator.ClearCart();
                return Redirect("/checkout/confirmation");
            }

            return View("~/Views/Checkout/Review.cshtml", model);
        }

        [HttpPost]
        public ActionResult Remove(PerformanceVM perf)
        {
            var mediator = new TicketMediator();
            var cart = mediator.GetCart();
            cart.Performances.RemoveAt(perf.LineNumber);

            int i = 0;
            foreach (var performance in cart.Performances)
            {
                perf.LineNumber = i;
                i++;
            }
            return Redirect("/checkout/cart");
        }

        public ActionResult Confirmation()
        {
            var mediator = new TicketMediator();
            CartVM cart = mediator.GetCart();
            mediator.ClearCart();

            decimal total = 0;
            foreach (var perf in cart.Performances)
            {
                total += (perf.Quantity * perf.Price);
            }
            cart.Total = total;
            return View(cart);
        }
    }
}

inetpub/Ticketing.Website/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ticketing.Framework.Mediators;
using Ticketing.Framework.Models.Cart;
using Ticketing.Framework.Models.Common;
using Ticketing.Framework.Models.Ticket;

namespace Ticketing.Website.Controllers
{
    public class EventController : Controller
    {
        public ActionResult EventDetails(int id)
        {
            var mediator = new TicketMediator();
            var model = mediator.GetEvent(id);
            //model.Performances = new List<PerformanceVM>();
            //model.Performances = mediator.GetPerformances(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult BuyTickets()
        {
            var mediator = new TicketMediator();
            var model = new BuyTicketsVM();
            model.Performances = new List<PerformanceVM>();
            model.Performances = mediator.GetAllPerformances();

            model.Categories = new List<Category>();
            model.Categories = mediator.GetEventTypes();
            model.Events = new List<EventItem>();
            model.Events = mediator.GetEventItems();
            model.FromDate = DateTime.Today.ToString("MM/dd/yyyy");
            return View(model);
        }

        //[HttpPost]
        //public ActionResult BuyTickets(string FromDate, string ToDate)
        //{
        //    var mediator = new TicketMediator();
        //    var model = new BuyTicketsVM();
        //    model.Performances = new List<PerformanceVM>();
        //    model.Performances = mediator.GetAllPerformances();

        //    model.Categories = new List<Category>();
        //    model.Categories = mediator.GetEventTypes();
        //    model.Events = new List<EventItem>();
        //    model.Events = mediator.GetEventItems();
        //    model.FromDate = DateTime.Today.ToString("MM/dd/yyyy");
        //    return View(model);
        //}

        public ActionResult EventList()
        {
            var mediator = new TicketMediator();
            List<EventVM> events = mediator.GetActiveEvents();
            return View(events);
        }

        public ActionResult AddToCart(PerformanceVM model)
        {
            var mediator = new TicketMediator();
            CartVM cart = mediator.GetCart();
            cart.Performances.Add(model);
            return Redirect("/Checkout/Cart");
        }

        [HttpPost]
        public ActionResult BuyTickets(BuyTicketsVM model)
        {
            var mediator = new TicketMediator();
            model.Performances = new List<PerformanceVM>();
            var perfs = mediator.GetAllPerformances();
            var fromDate = DateTime.Parse(model.FromDate);
            var toDate = fromDate.AddYears(1);
            if (!string.IsNullOrEmpty(model.ToDate))
                toDate = DateTime.Parse(model.ToDate).AddHours(1);

            perfs = perfs.Where(p => DateTime.Parse(p.PerformanceDate) > fromDate && DateTime.Parse(p.PerformanceDate) < toDate).ToList();
            
            var selectedEventType = model.Events.Where(p => p.SelectedIndicator).Select(e => e.EventId);
            var selectedCategoryType = model.Categories.Where(p => p.SelectedIndicator).Select(e => e.CategoryId);

            if (selectedEventType.Count() > 0)
                perfs = perfs.Where(p => selectedEventType.Contains(p.EventId)).ToList();

            if (selectedCategoryType.Count() > 0 && (perfs != null && perfs.Count > 0))
                perfs = perfs.Where(p => selectedCategoryType.Contains(p.EventId)).ToList();


            model.Performances = perfs;
            return View(model);
        }

    }
}

inetpub/Ticketing.Website/Views/Shared/Address.cshtml
@model Ticketing.Framework.BusinessModels.Address
@{
    ViewBag.Title = "Address";
}

<h2>Address</h2>

<div class="editor-label">
    @Html.LabelFor(l => l.Address1, "Address")
</div>
<div class="editor-field">
    @Html.TextBoxFor(l => l.Address1, new { required = "" })
</div>
<div class="editor-label">
    @Html.LabelFor(l => l.Address2, "Address cont.")
</div>
<div class="editor-field">
    @Html.TextBoxFor(l => l.Address2)
</div>
<div class="editor-label">
    @Html.LabelFor(l => l.City, "City")
</div>
<div class="editor-field">
    @Html.TextBoxFor(l => l.City, new { required = "" })
</div>
<div class="editor-label">
    @Html.LabelFor(l => l.State, "State")
</div>
<div class="editor-field">
    @Html.TextBoxFor(l => l.State, new { required = "" })
</div>
<div class="editor-label">
    @Html.LabelFor(l => l.Zip, "Zip")
</div>
<div class="editor-field">
    @Html.TextBoxFor(l => l.Zip, new { required = "" })
</div>

inetpub/Ticketing.Website/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title"><a href="/"><img src="/Images/ABMZ_logo2.png" alt="Logo" /></a></p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Buy Tickets", "BuyTickets", "Event")</li>
                        <li>@Html.ActionLink("Events", "EventList", "Event")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Cart", "Cart", "Checkout")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>@DateTime.Now.Year - Ticketing Website</p>
                </div>
            </div>
        </footer>
        @Scripts.Render("~/bundles/custom")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

inetpub/Ticketing.Website/Views/Shared/Error404.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>The page you are looking for does not exist.</h2>
    </hgroup>
</body>
</html>

inetpub/Ticketing.Website/Views/Shared/NotFound.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>The page you are looking for does not exist.</h2>
    </hgroup>
</body>
</html>

inetpub/Ticketing.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title"><a href="/"><img src="/Images/ABMZ_logo2.png" alt="Logo" /></a></p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Buy Tickets", "BuyTickets", "Event")</li>
                        <li>@Html.ActionLink("Events", "EventList", "Event")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Cart", "Cart", "Checkout")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>@DateTime.Now.Year - Ticketing Website</p>
                </div>
            </div>
        </footer>
        @Scripts.Render("~/bundles/custom")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>